### PR TITLE
Added script that runs immediately on RTM_NEWLINK

### PR DESCRIPTION
**Pull request by jgrindstaff-at**
**Description**
Created a new script that runs when there is a new link. This script is blocking and allows for some activity before waiting for DHCP.

**For Developers**
Make sure that you have done all of the steps necessary to merge a PR:
- [x] My code follows the coding style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated and created tests accordingly.
- [ ] My PR is linked to an issue.
- [ ] The PR fully addresses the issue, or follow up issues are created.

**For Reviewers**
- [ ] Are the tests that need to be updated changed?
- [ ] Does the code conform to the standards of the project?
- [ ] Is the design consistent with the architecture of the project?

**Additional context**
Add any other context or screenshots about the pull request here.

### CODE REVIEW

**Comment by jgrindstaff-at** [comment]
@nZac It looks like the documentation in the `README.md` is suggesting the environment variables take paths as arguments - but in the implementation it looks like the expectation is for the value to be anything that can be passed to a system call - a much broader category of input than a path.

For example:
`Environment=NETREACT_UP_SCRIPT='/abs/path/to/toUpScript'`

Should probably be:
`Environment=NETREACT_UP_SCRIPT='<any valid system call statements>'`

Or something like that. Because the arguments need not be a path specifically and can be any chunk of commands that would be valid if passed to a system call.

I'm not sure I know exactly what I would want the change to be yet, but do you see any point to this?

**Comment by nZac** [comment]
I good with you updating the readme if that is what you are asking.

**Review by TheBengineer — COMMENTED** [review]
Looking into how this works.

**Comment by jgrindstaff-at** [comment]
@nZac I would also like the PR reviewed if you have time.

**Review by nZac — APPROVED** [review]
This looks good to me.

**Pull request merged**
